branch-defaults:
  main:
    environment: vartana-staging
    group_suffix: null
  production:
    environment: vartana-production
environment-defaults:
  vartana-staging:
    branch: null
    repository: null
global:
  application_name: vartana-server
  branch: null
  default_ec2_keyname: vartana-eb-staging
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
