module GraphqlHelper
  ERRORS = {
    'SERVER_ERROR': 'INTERNAL_SERVER_ERROR',
    'VALIDATION_ERROR': 'VALIDATION_ERROR',
    'NOT_FOUND': 'NOT_FOUND',
    'AUTHENTICATION_ERROR': 'AUTHENTICATION_ERROR',
  }.freeze
end
